name: fatl_mlkit_demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  camera: ^0.10.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  google_mlkit_pose_detection: ^0.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
